name: Generate documentation
on: [push]
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - name: Build documents
        run: npx ts-node scripts/generate-puml.ts
      - name: Commit changes
        run: |
          git config --global user.name 'fisbot'
          git config --global user.email 'fisbot@users.noreply.github.com'
          git diff-index --quiet HEAD || (git add . && git commit -m'[bot] generated docs' --allow-empty && git push -f)
