name: Generate documentation
on: [push]
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - name: Build documents
        run: npx ts-node scripts/generate-puml.ts
      - name: Commit changes
        run: |
          git config --global user.name 'bot'
          git config --global user.email 'bot@users.noreply.github.com'
          git commit -am "Generated documentation"
          git push